<Project Sdk="Microsoft.NET.Sdk">

  <!-- Targets -->
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <!-- Build -->
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <!-- Package info -->
  <PropertyGroup>
    <Description>Inter-process communication over named pipes for .NET. Provides a request/response server, a client and an optional client connection pool.</Description>
    <PackageTags>ipc; named-pipes; pipes; inter-process-communication; client-server; messaging; netstandard</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <!-- Usings -->
  <ItemGroup>
    <Using Include="JetBrains.Annotations" />
  </ItemGroup>

</Project>
